export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";
export const GET_COUNTRIES_ERROR = "GET_COUNTRIES_ERROR";
export const GET_COUNTRY_DATA = "GET_COUNTRY_DATA";
export const GET_COUNTRY_DATA_SUCCESS = "GET_COUNTRY_DATA_SUCCESS";
export const GET_COUNTRY_DATA_ERROR = "GET_COUNTRY_DATA_ERROR";
